# Model parameters
use_transpose_conv: False
interp_mode: nearest
upsampling_kernel_size: 5

# Loss parameters
a_reconst: 10.
lambda1_recons: 60.
lambda2_feat: 10.
use_perceptual_loss: True

# Optimizer parameters
lr: 2.e-4
b1: 0.5
b2: 0.999

# Training setup
max_epochs: 0
batch_size: 4
gpus: [1]
log_every_n_steps: 10
check_val_every_n_epoch: 1
sample_images_every_n_epoch: 10

# Dataset directory
data_dir: datasets

# Intermediary models
vae1_ckpt_path: "vae1.ckpt"
vae2_ckpt_path: "vae2.ckpt"

